// AUTO-GENERATED by scripts/import-monsters.mjs. Do not edit by hand.
// Source: /home/rxtxr/projects/artworks/archive/monsters/
// Entries: 75 sidecars → 39 single-mutation, 75 multi-mutation
// Generated: 2026-04-19T21:00:41.058Z

// Eager glob: Vite inlines every PNG's final URL at build time. In dev, the
// dev server serves them from src/assets/monsters/. In prod, they're bundled
// with content hashes under /assets/.
const urls = import.meta.glob('../assets/monsters/*.png', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

function resolveUrl(hash: string): string | undefined {
  return urls[`../assets/monsters/${hash}.png`];
}

export interface AtlasEntry {
  id: string;
  level: number;
  url: string;
}

export interface MultiAtlasEntry {
  mutations: { id: string; level: number }[];
  url: string;
  /** Score vs a query set — lower is closer. Filled in by lookupMulti. */
  score?: number;
}

interface RawSingle { id: string; level: number; hash: string }
interface RawMulti  { hash: string; mutations: { id: string; level: number }[] }

const BY_STATE: Record<string, RawSingle> = {
  'chitin_plate:1': { id: 'chitin_plate', level: 1, hash: '381eb31589ed' },
  'chitin_plate:3': { id: 'chitin_plate', level: 3, hash: '4922845665c1' },
  'chitin_plate:5': { id: 'chitin_plate', level: 5, hash: '6cc45049000c' },
  'claws:1': { id: 'claws', level: 1, hash: '5c87e2c564d1' },
  'claws:3': { id: 'claws', level: 3, hash: '37f0bfcac261' },
  'claws:5': { id: 'claws', level: 5, hash: 'dd01d63f1fb6' },
  'electric_organ:1': { id: 'electric_organ', level: 1, hash: '15869e7bc285' },
  'electric_organ:3': { id: 'electric_organ', level: 3, hash: '551af8ff1121' },
  'electric_organ:5': { id: 'electric_organ', level: 5, hash: '95459a7fd4a1' },
  'fire_sac:1': { id: 'fire_sac', level: 1, hash: '31c336260a4a' },
  'fire_sac:3': { id: 'fire_sac', level: 3, hash: '2ebcd78cf62c' },
  'fire_sac:5': { id: 'fire_sac', level: 5, hash: '17638b9a92fe' },
  'horns:1': { id: 'horns', level: 1, hash: 'b65561b553d1' },
  'horns:3': { id: 'horns', level: 3, hash: '4600e93ed0f3' },
  'horns:5': { id: 'horns', level: 5, hash: 'f21d3e1b1fc4' },
  'keen_senses:1': { id: 'keen_senses', level: 1, hash: '712bf7e9a26c' },
  'keen_senses:3': { id: 'keen_senses', level: 3, hash: '2d4a24cc8f1e' },
  'keen_senses:5': { id: 'keen_senses', level: 5, hash: '6c264412f53c' },
  'leather_hide:1': { id: 'leather_hide', level: 1, hash: 'c5f5abdb928d' },
  'leather_hide:3': { id: 'leather_hide', level: 3, hash: '2d0bec1c0de0' },
  'leather_hide:5': { id: 'leather_hide', level: 5, hash: '33ce060fc2fc' },
  'magma_crust:1': { id: 'magma_crust', level: 1, hash: '824ecd275356' },
  'magma_crust:3': { id: 'magma_crust', level: 3, hash: '8324c6aea93a' },
  'magma_crust:5': { id: 'magma_crust', level: 5, hash: '65cc635ec093' },
  'poison_gland:1': { id: 'poison_gland', level: 1, hash: 'e0053e5933d9' },
  'poison_gland:3': { id: 'poison_gland', level: 3, hash: '968c79fdefd9' },
  'poison_gland:5': { id: 'poison_gland', level: 5, hash: '0b08f1ad602d' },
  'stone_skin:1': { id: 'stone_skin', level: 1, hash: '6ed59504119d' },
  'stone_skin:3': { id: 'stone_skin', level: 3, hash: 'cbe1aa57eaf6' },
  'stone_skin:5': { id: 'stone_skin', level: 5, hash: 'baca716f9a1e' },
  'thunder_strike:1': { id: 'thunder_strike', level: 1, hash: '768d8d60869b' },
  'thunder_strike:3': { id: 'thunder_strike', level: 3, hash: 'f14291b437a7' },
  'thunder_strike:5': { id: 'thunder_strike', level: 5, hash: 'f4f1dc0ef1ba' },
  'venom_claws:1': { id: 'venom_claws', level: 1, hash: '604a02145b73' },
  'venom_claws:3': { id: 'venom_claws', level: 3, hash: 'ae007da2bd85' },
  'venom_claws:5': { id: 'venom_claws', level: 5, hash: 'e18bc455dda8' },
  'wings:1': { id: 'wings', level: 1, hash: 'f36c8a64033f' },
  'wings:3': { id: 'wings', level: 3, hash: 'b02c5f5bcac2' },
  'wings:5': { id: 'wings', level: 5, hash: '04dcc7cc9a8b' },
};

const BY_MULTI: Record<string, RawMulti> = {
  'chitin_plate:1': { hash: '381eb31589ed', mutations: [{ id: 'chitin_plate', level: 1 }] },
  'chitin_plate:1|claws:1|horns:1|keen_senses:1|leather_hide:1': { hash: '04cc1fcea12d', mutations: [{ id: 'claws', level: 1 }, { id: 'horns', level: 1 }, { id: 'chitin_plate', level: 1 }, { id: 'leather_hide', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'chitin_plate:1|claws:1|horns:1|leather_hide:1': { hash: 'ce96a01e6e11', mutations: [{ id: 'horns', level: 1 }, { id: 'chitin_plate', level: 1 }, { id: 'leather_hide', level: 1 }, { id: 'claws', level: 1 }] },
  'chitin_plate:1|electric_organ:1|horns:1': { hash: '595cfd40efab', mutations: [{ id: 'chitin_plate', level: 1 }, { id: 'electric_organ', level: 1 }, { id: 'horns', level: 1 }] },
  'chitin_plate:1|fire_sac:1|horns:1|leather_hide:1': { hash: 'a20321ef154b', mutations: [{ id: 'horns', level: 1 }, { id: 'fire_sac', level: 1 }, { id: 'chitin_plate', level: 1 }, { id: 'leather_hide', level: 1 }] },
  'chitin_plate:1|horns:1|leather_hide:1|stone_skin:1': { hash: '65ab526f4741', mutations: [{ id: 'horns', level: 1 }, { id: 'chitin_plate', level: 1 }, { id: 'stone_skin', level: 1 }, { id: 'leather_hide', level: 1 }] },
  'chitin_plate:1|horns:1|stone_skin:1': { hash: 'fcd69418f855', mutations: [{ id: 'chitin_plate', level: 1 }, { id: 'horns', level: 1 }, { id: 'stone_skin', level: 1 }] },
  'chitin_plate:3': { hash: '4922845665c1', mutations: [{ id: 'chitin_plate', level: 3 }] },
  'chitin_plate:3|horns:3|stone_skin:1': { hash: '708e04f46ce4', mutations: [{ id: 'chitin_plate', level: 3 }, { id: 'horns', level: 3 }, { id: 'stone_skin', level: 1 }] },
  'chitin_plate:3|horns:3|stone_skin:3': { hash: '8f480c28ab1c', mutations: [{ id: 'chitin_plate', level: 3 }, { id: 'horns', level: 3 }, { id: 'stone_skin', level: 3 }] },
  'chitin_plate:3|leather_hide:3|stone_skin:3': { hash: 'db7a4f900f6a', mutations: [{ id: 'stone_skin', level: 3 }, { id: 'chitin_plate', level: 3 }, { id: 'leather_hide', level: 3 }] },
  'chitin_plate:5': { hash: '6cc45049000c', mutations: [{ id: 'chitin_plate', level: 5 }] },
  'chitin_plate:5|horns:5|stone_skin:3': { hash: '01ccc09a4a56', mutations: [{ id: 'chitin_plate', level: 5 }, { id: 'horns', level: 5 }, { id: 'stone_skin', level: 3 }] },
  'claws:1': { hash: '5c87e2c564d1', mutations: [{ id: 'claws', level: 1 }] },
  'claws:1|electric_organ:1|fire_sac:1|horns:1|keen_senses:1|wings:1': { hash: 'd7cb3ac911ee', mutations: [{ id: 'claws', level: 1 }, { id: 'fire_sac', level: 1 }, { id: 'electric_organ', level: 1 }, { id: 'wings', level: 1 }, { id: 'horns', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:1|electric_organ:1|keen_senses:1|wings:1': { hash: 'e117162dfd5c', mutations: [{ id: 'claws', level: 1 }, { id: 'electric_organ', level: 1 }, { id: 'wings', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:1|fire_sac:1|keen_senses:1|poison_gland:1': { hash: 'd76bfbba9bc3', mutations: [{ id: 'claws', level: 1 }, { id: 'poison_gland', level: 1 }, { id: 'fire_sac', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:1|horns:1|keen_senses:1|wings:1': { hash: '9587151d1857', mutations: [{ id: 'claws', level: 1 }, { id: 'horns', level: 1 }, { id: 'wings', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:1|horns:1|stone_skin:1': { hash: '070d3b378868', mutations: [{ id: 'claws', level: 1 }, { id: 'horns', level: 1 }, { id: 'stone_skin', level: 1 }] },
  'claws:1|keen_senses:1|leather_hide:1|poison_gland:1': { hash: '4b525bc26c73', mutations: [{ id: 'claws', level: 1 }, { id: 'poison_gland', level: 1 }, { id: 'leather_hide', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:1|keen_senses:1|leather_hide:1|poison_gland:1|wings:1': { hash: 'be9483374689', mutations: [{ id: 'claws', level: 1 }, { id: 'poison_gland', level: 1 }, { id: 'wings', level: 1 }, { id: 'leather_hide', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:1|keen_senses:1|leather_hide:1|wings:1': { hash: '599e4ea3b78f', mutations: [{ id: 'wings', level: 1 }, { id: 'keen_senses', level: 1 }, { id: 'claws', level: 1 }, { id: 'leather_hide', level: 1 }] },
  'claws:1|keen_senses:1|poison_gland:1': { hash: 'b2b781e8b699', mutations: [{ id: 'poison_gland', level: 1 }, { id: 'claws', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'claws:2|keen_senses:1|poison_gland:3': { hash: 'b65c6e1e5f61', mutations: [{ id: 'poison_gland', level: 3 }, { id: 'claws', level: 2 }, { id: 'keen_senses', level: 1 }] },
  'claws:3': { hash: '37f0bfcac261', mutations: [{ id: 'claws', level: 3 }] },
  'claws:3|fire_sac:5|keen_senses:3': { hash: '789808fbea04', mutations: [{ id: 'fire_sac', level: 5 }, { id: 'claws', level: 3 }, { id: 'keen_senses', level: 3 }] },
  'claws:3|keen_senses:3|poison_gland:5': { hash: 'cb6ad0a24c8d', mutations: [{ id: 'poison_gland', level: 5 }, { id: 'claws', level: 3 }, { id: 'keen_senses', level: 3 }] },
  'claws:3|keen_senses:3|wings:3': { hash: '071590423a15', mutations: [{ id: 'wings', level: 3 }, { id: 'claws', level: 3 }, { id: 'keen_senses', level: 3 }] },
  'claws:3|poison_gland:3': { hash: '3d283a331134', mutations: [{ id: 'claws', level: 3 }, { id: 'poison_gland', level: 3 }] },
  'claws:3|poison_gland:3|venom_claws:3': { hash: '715275a4751f', mutations: [{ id: 'claws', level: 3 }, { id: 'poison_gland', level: 3 }, { id: 'venom_claws', level: 3 }] },
  'claws:5': { hash: 'dd01d63f1fb6', mutations: [{ id: 'claws', level: 5 }] },
  'claws:5|horns:5|stone_skin:1': { hash: '1b1446ea6a2e', mutations: [{ id: 'claws', level: 5 }, { id: 'horns', level: 5 }, { id: 'stone_skin', level: 1 }] },
  'electric_organ:1': { hash: '15869e7bc285', mutations: [{ id: 'electric_organ', level: 1 }] },
  'electric_organ:1|keen_senses:1|poison_gland:1|wings:1': { hash: '5fbe96bc76c7', mutations: [{ id: 'wings', level: 1 }, { id: 'electric_organ', level: 1 }, { id: 'keen_senses', level: 1 }, { id: 'poison_gland', level: 1 }] },
  'electric_organ:1|keen_senses:1|wings:1': { hash: '0b1963d6f215', mutations: [{ id: 'electric_organ', level: 1 }, { id: 'wings', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'electric_organ:3': { hash: '551af8ff1121', mutations: [{ id: 'electric_organ', level: 3 }] },
  'electric_organ:3|keen_senses:2|wings:3': { hash: '26f1e1fd6406', mutations: [{ id: 'electric_organ', level: 3 }, { id: 'wings', level: 3 }, { id: 'keen_senses', level: 2 }] },
  'electric_organ:3|thunder_strike:3|wings:3': { hash: '917b61935ba2', mutations: [{ id: 'electric_organ', level: 3 }, { id: 'wings', level: 3 }, { id: 'thunder_strike', level: 3 }] },
  'electric_organ:3|wings:3': { hash: 'd8e2ac668ecd', mutations: [{ id: 'electric_organ', level: 3 }, { id: 'wings', level: 3 }] },
  'electric_organ:5': { hash: '95459a7fd4a1', mutations: [{ id: 'electric_organ', level: 5 }] },
  'electric_organ:5|keen_senses:3|wings:5': { hash: '1d03d601f855', mutations: [{ id: 'electric_organ', level: 5 }, { id: 'wings', level: 5 }, { id: 'keen_senses', level: 3 }] },
  'fire_sac:1': { hash: '31c336260a4a', mutations: [{ id: 'fire_sac', level: 1 }] },
  'fire_sac:1|horns:1|keen_senses:1|stone_skin:1': { hash: 'f46685e152ac', mutations: [{ id: 'stone_skin', level: 1 }, { id: 'fire_sac', level: 1 }, { id: 'horns', level: 1 }, { id: 'keen_senses', level: 1 }] },
  'fire_sac:3': { hash: '2ebcd78cf62c', mutations: [{ id: 'fire_sac', level: 3 }] },
  'fire_sac:3|horns:3': { hash: '682e032e05c7', mutations: [{ id: 'fire_sac', level: 3 }, { id: 'horns', level: 3 }] },
  'fire_sac:3|magma_crust:3|stone_skin:3': { hash: 'bb7c7a486c32', mutations: [{ id: 'stone_skin', level: 3 }, { id: 'fire_sac', level: 3 }, { id: 'magma_crust', level: 3 }] },
  'fire_sac:5': { hash: '17638b9a92fe', mutations: [{ id: 'fire_sac', level: 5 }] },
  'horns:1': { hash: 'b65561b553d1', mutations: [{ id: 'horns', level: 1 }] },
  'horns:1|keen_senses:1|leather_hide:1|stone_skin:1': { hash: '7397515e6d63', mutations: [{ id: 'stone_skin', level: 1 }, { id: 'leather_hide', level: 1 }, { id: 'keen_senses', level: 1 }, { id: 'horns', level: 1 }] },
  'horns:3': { hash: '4600e93ed0f3', mutations: [{ id: 'horns', level: 3 }] },
  'horns:5': { hash: 'f21d3e1b1fc4', mutations: [{ id: 'horns', level: 5 }] },
  'keen_senses:1': { hash: '712bf7e9a26c', mutations: [{ id: 'keen_senses', level: 1 }] },
  'keen_senses:3': { hash: '2d4a24cc8f1e', mutations: [{ id: 'keen_senses', level: 3 }] },
  'keen_senses:5': { hash: '6c264412f53c', mutations: [{ id: 'keen_senses', level: 5 }] },
  'leather_hide:1': { hash: 'c5f5abdb928d', mutations: [{ id: 'leather_hide', level: 1 }] },
  'leather_hide:3': { hash: '2d0bec1c0de0', mutations: [{ id: 'leather_hide', level: 3 }] },
  'leather_hide:5': { hash: '33ce060fc2fc', mutations: [{ id: 'leather_hide', level: 5 }] },
  'magma_crust:1': { hash: '824ecd275356', mutations: [{ id: 'magma_crust', level: 1 }] },
  'magma_crust:3': { hash: '8324c6aea93a', mutations: [{ id: 'magma_crust', level: 3 }] },
  'magma_crust:5': { hash: '65cc635ec093', mutations: [{ id: 'magma_crust', level: 5 }] },
  'poison_gland:1': { hash: 'e0053e5933d9', mutations: [{ id: 'poison_gland', level: 1 }] },
  'poison_gland:3': { hash: '968c79fdefd9', mutations: [{ id: 'poison_gland', level: 3 }] },
  'poison_gland:5': { hash: '0b08f1ad602d', mutations: [{ id: 'poison_gland', level: 5 }] },
  'stone_skin:1': { hash: '6ed59504119d', mutations: [{ id: 'stone_skin', level: 1 }] },
  'stone_skin:3': { hash: 'cbe1aa57eaf6', mutations: [{ id: 'stone_skin', level: 3 }] },
  'stone_skin:5': { hash: 'baca716f9a1e', mutations: [{ id: 'stone_skin', level: 5 }] },
  'thunder_strike:1': { hash: '768d8d60869b', mutations: [{ id: 'thunder_strike', level: 1 }] },
  'thunder_strike:3': { hash: 'f14291b437a7', mutations: [{ id: 'thunder_strike', level: 3 }] },
  'thunder_strike:5': { hash: 'f4f1dc0ef1ba', mutations: [{ id: 'thunder_strike', level: 5 }] },
  'venom_claws:1': { hash: '604a02145b73', mutations: [{ id: 'venom_claws', level: 1 }] },
  'venom_claws:3': { hash: 'ae007da2bd85', mutations: [{ id: 'venom_claws', level: 3 }] },
  'venom_claws:5': { hash: 'e18bc455dda8', mutations: [{ id: 'venom_claws', level: 5 }] },
  'wings:1': { hash: 'f36c8a64033f', mutations: [{ id: 'wings', level: 1 }] },
  'wings:3': { hash: 'b02c5f5bcac2', mutations: [{ id: 'wings', level: 3 }] },
  'wings:5': { hash: '04dcc7cc9a8b', mutations: [{ id: 'wings', level: 5 }] },
};

/**
 * Single-mutation lookup with level fallback.
 * Tries exact level first, then nearby levels (L2 → L1/L3, etc.).
 */
export function lookupAtlas(id: string, level: number): AtlasEntry | null {
  const tryLevels = [level, level - 1, level + 1, level - 2, level + 2];
  for (const l of tryLevels) {
    if (l < 1 || l > 5) continue;
    const raw = BY_STATE[`${id}:${l}`];
    if (!raw) continue;
    const url = resolveUrl(raw.hash);
    if (url) return { id: raw.id, level: raw.level, url };
  }
  return null;
}

/**
 * Multi-mutation lookup.
 *   - exact set+level match wins outright
 *   - else: same id-set, levels nearby → distance-scored
 * Returns null if no entry has the same set of mutation ids.
 */
export function lookupMulti(
  mutations: { id: string; level: number }[],
): MultiAtlasEntry | null {
  if (mutations.length === 0) return null;
  const queryIds = [...mutations].map((m) => m.id).sort().join('|');
  const queryByLevel = new Map(mutations.map((m) => [m.id, m.level]));

  let best: { entry: RawMulti; score: number } | null = null;
  for (const entry of Object.values(BY_MULTI)) {
    if (entry.mutations.length !== mutations.length) continue;
    const entryIds = [...entry.mutations].map((m) => m.id).sort().join('|');
    if (entryIds !== queryIds) continue;

    let score = 0;
    for (const em of entry.mutations) {
      const q = queryByLevel.get(em.id);
      if (q === undefined) { score = Number.POSITIVE_INFINITY; break; }
      score += Math.abs(q - em.level);
    }
    if (best === null || score < best.score) best = { entry, score };
  }
  if (!best) return null;
  const url = resolveUrl(best.entry.hash);
  if (!url) return null;
  return {
    mutations: best.entry.mutations,
    url,
    score: best.score,
  };
}

export const ATLAS_STATES = Object.keys(BY_STATE);
export const ATLAS_MULTI_KEYS = Object.keys(BY_MULTI);
